version: "2"

services: 
  auth_service_db:
    image: mysql:5.6.26
    container_name: auth_service_db
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 'P@ssw0rd'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'P@ssw0rd'
      MYSQL_DATABASE: auth-db-local
      MYSQL_ROOT_HOST: '%'
    ports:
      - '33070:3306'
    expose:
      - '33070'
    volumes:
      - auth-service-db:/var/lib/mysql
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth_service
    restart: on-failure
    volumes:
      - .:/auth-service
    environment:
      - ACCOUNT_DATABASE_HOST=auth_service_db
      - ACCOUNT_DATABASE_PORT=33070
      - ACCOUNT_DATABASE_USER=root
      - ACCOUNT_DATABASE_PASSWORD=P@ssw0rd
      - ACCOUNT_DATABASE_NAME=auth-db-local
      - SECRET_KEY_JWT=RaH4si4Sekaleh
      - REDIS_URL
      - ADMIN_ACCOUNT_USERNAME="Dea Dania"
      - ADMIN_ACCOUNT_EMAIL="deadania14@gmail.com"
      - ADMIN_ACCOUNT_PASSWORD="P@ssw0rd!!"
      - PORT_RUN="8080"
    ports:
      - "8080:8080"
volumes:
  auth-service-db:
networks:
  metalitnet:
    driver: bridge